include: package:very_good_analysis/analysis_options.3.0.0.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"